spring:
  application:
    name: turbine

  #给一个服务配置2个端口，2003，一个访问端口2002
server:
  port: 2002
management:
  port: 2003
eureka:
  instance:
    hostname: 192.168.98.188
    ip-address: 192.168.98.188
  client:
    service-url:
      defaultZone: http://peer1:8083/eureka/

#配置Eureka中的serviceId列表，表明监控哪些服务(服务消费者),多个服务用逗号隔开
turbine:
  app-config: feign-consumer
  #指定了集群名称为default，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群
  cluster-name-expression: "default"
  #turbine.combine-host-port 参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务
  #这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计
  combine-host-port: true
